name: CI/CD Microservicio Backend (Ventas)

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build imagen Backend y push a ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: back_ventas
          IMAGE_TAG: latest
        run: |
          docker build -t backend-temp .
          docker tag backend-temp:latest $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

      - name: Desplegar BD y Backend con Compose vía SSM
        run: |
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          REPO=back_ventas
          
          COMPOSE_B64=$(cat docker-compose.yml | base64 -w 0)
          
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Despliegue Infraestructura como Código (Docker Compose)" \
            --parameters "{\"commands\":[
              \"set -e\",
              
              \"echo 1. Creando directorio de trabajo...\",
              \"mkdir -p /home/ssm-user/app-ventas\",
              \"cd /home/ssm-user/app-ventas\",
              
              \"echo 2. Autenticando en ECR...\",
              \"aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY\",
              
              \"echo 3. Reconstruyendo docker-compose.yml en EC2...\",
              \"echo $COMPOSE_B64 | base64 -d > docker-compose.yml\",
              
              \"echo 4. Exportando variables de entorno...\",
              \"export REGISTRY=$REGISTRY\",
              \"export REPO=$REPO\",
              \"export DB_NAME=${{ secrets.DB_NAME }}\",
              \"export DB_USER=${{ secrets.DB_USER }}\",
              \"export DB_PASSWORD=${{ secrets.DB_PASSWORD }}\",
              
              \"echo 5. Desplegando Orquestación...\",
              \"docker compose pull\",
              \"docker compose down\",
              \"docker compose up -d\",
              
              \"echo 6. Limpiando residuos...\",
              \"docker image prune -f\"
            ]}" \
            --output text
