name: CI/CD Backend Ventas a ECR

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build imagen Backend y push a ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: innovatech-backend-ventas
          IMAGE_TAG: latest
        run: |
          docker build -t backend-ventas-temp .
          docker tag backend-ventas-temp:latest $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

      - name: Conectar con el Clúster EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name innovatech-cluster

      - name: Aplicar Cambios en Kubernetes
        run: |
          kubectl apply -f k8s/backend-ventas.yaml

      - name: Forzar Descarga de Imagen Nueva (Rollout)
        run: |
          kubectl rollout restart deployment/backend-ventas
